### ISSUE TITLE
Webjar locator throws IllegalStateException when adding sbt-web to the project

### ISSUE THREAD

**Issue by akkie** [sbt/sbt-web#104]
If I add sbt-web to my project which uses webjars then the [webjar-locator](https://github.com/webjars/webjars-locator) throws the following exception:

```
Caused by: java.lang.IllegalStateException: Got deeper than 5 levels while searching /home/christian/projects/my.project/target/web/classes/main/META-INF/resources/webjars
    at org.webjars.urlprotocols.FileUrlProtocolHandler.aggregateChildren(FileUrlProtocolHandler.java:43)
    at org.webjars.urlprotocols.FileUrlProtocolHandler.aggregateChildren(FileUrlProtocolHandler.java:47)
    at org.webjars.urlprotocols.FileUrlProtocolHandler.aggregateChildren(FileUrlProtocolHandler.java:47)
    at org.webjars.urlprotocols.FileUrlProtocolHandler.aggregateChildren(FileUrlProtocolHandler.java:47)
    at org.webjars.urlprotocols.FileUrlProtocolHandler.aggregateChildren(FileUrlProtocolHandler.java:47)
    at org.webjars.urlprotocols.FileUrlProtocolHandler.aggregateChildren(FileUrlProtocolHandler.java:47)
    at org.webjars.urlprotocols.FileUrlProtocolHandler.aggregateChildren(FileUrlProtocolHandler.java:47)
    at org.webjars.urlprotocols.FileUrlProtocolHandler.listFiles(FileUrlProtocolHandler.java:36)
    at org.webjars.urlprotocols.FileUrlProtocolHandler.getAssetPaths(FileUrlProtocolHandler.java:25)
    at org.webjars.WebJarAssetLocator.getAssetPaths(WebJarAssetLocator.java:80)
    at org.webjars.WebJarAssetLocator.getFullPathIndex(WebJarAssetLocator.java:106)
    at controllers.WebJarAssets.<init>(WebJarAssets.scala:26)
    at controllers.WebJarAssets$.<init>(WebJarAssets.scala:66)
    at controllers.WebJarAssets$.<clinit>(WebJarAssets.scala)
```

This issue occurs only during controller testing if the directory structure of the assets has a nesting level deeper than 5.

I've created a small project which reproduces the issue: https://github.com/akkie/webjar-bug

**Comment by huntc** [comment]
Has the webjars locator that sbt-web depends on been evicted by a later one pulled in by webjars-play?

`sbt evicted` should show the evicted libraries.

/cc @jamesward

**Comment by jamesward** [comment]
Shouldn't the plugin level dependencies be able to different from the project level dependencies?

**Comment by huntc** [comment]
Good point!

**Comment by azhuchkov** [comment]
+1 for the issue.

My configuration:
Play 2.3.9
Scala 2.11.6
Sbt 0.13.5
webjars-play  2.3.0-3

**Comment by jamesward** [comment]
I've increased the limit: https://github.com/webjars/webjars-locator/issues/77#issuecomment-108125656

Not sure what impact that will have.  But might be a suitable workaround for now.

**Comment by mkurz** [comment]
Not relevant anymore since the code that checked for the depth got removed anyway and there was quite some refactoring going on: https://github.com/webjars/webjars-locator-core/pull/28/files#diff-524cd0b7f7aed4b3fbe1cd3c2d7ee788992a70e8b3920db52900abbb9aa7bfa7L60
