### ISSUE TITLE
sbt-web fails under sbt 1.3.0-RC1

### ISSUE THREAD

**Issue by pshirshov** [sbt/sbt-web#171]
Classloading policy changes lead to errors like this:

```
[ERROR] [SECURITY][05/16/2019 21:38:35.956] [sbt-web-akka.actor.default-dispatcher-2] [akka.actor.ActorSystemImpl(sbt-web)] Uncaught error from thread [sbt-web-akka.actor.default-dispatcher-2]: scala/concurrent/Future$$anon$1, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[sbt-web]
java.lang.NoClassDefFoundError: scala/concurrent/Future$$anon$1
	at scala.concurrent.Future$.firstCompletedOf(Future.scala:683)
	at akka.actor.CoordinatedShutdown.loop$1(CoordinatedShutdown.scala:382)
	at akka.actor.CoordinatedShutdown.$anonfun$run$6(CoordinatedShutdown.scala:387)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: scala.concurrent.Future$$anon$1
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 17 more
```

relevant: https://github.com/sbt/sbt/issues/4691

**Comment by kennydaniel** [comment]
Fixed in https://github.com/sbt/sbt/pull/4729

@pshirshov want to close issue?

**Comment by mkurz** [comment]
I set up [GitHub actions workflow that tests against sbt 1.9.0](https://github.com/sbt/sbt-web/actions/runs/4996176652/jobs/8949035935), so this can be closed for sure.
